### ISSUE TITLE
Flow not updating / detecting errors

### ISSUE THREAD

**Issue by altdeveloper** [SublimeLinter/SublimeLinter-flow#10]
Hi there,

Sublimelinter flow doesn't seem to detect when there are errors, even when i have introduced them. 

Here is the console

SublimeLinter: flow: test.js ['/usr/local/bin/flow', 'check', '--show-all-errors'] 
SublimeLinter: flow output:

Found 0 errors 

but there is clearly an error, at some point it suddenly detects an error usually when i am playing around with changing the sublime linter theme. Then once the error is shown I correct the error but sublimelinter flow doesn't detect that its fixed. It still says there is an error. I have saved the file also.

Of course running it in the shell always works .. heres the details of the shell

Flow server launched for /Users/ian/Desktop/start/flight
Spawned flow server (child pid=1267)
Logs will go to /var/folders/wp/7fvln53n0zzbnqply2rp7_bh0000gn/T/flow_ian/ian-zSUserszSianzSDesktopzSstartzSflight.log
The flow server will be ready in a moment.

/Users/ian/Desktop/start/flight/test.js:7:5,11: string
This type is incompatible with
  /Users/ian/Desktop/start/flight/test.js:4:10,15: number

Found 1 error

I do have jshint and also jscs installed via sublimelinter and they work ok.

Any reason why flow isn't picking / detecting changes ?

Thanks

heres my standard .flowconfig

[ignore]

[include]

[libs]

[options]

**Comment by NicoSantangelo** [comment]
Hmm, running the same command as the linter ( `/usr/local/bin/flow check --show-all-errors` ) outputs the correct results on the Terminal?

If it does, does it takes a really long time to do it?

**Comment by altdeveloper** [comment]
Hi.

The command line appears to produce the correct result.. ie.. and its very quick.

➜  flight git:(fff) ✗ /usr/local/bin/flow check --show-all-errors

Found 0 errors

I have just corrected a mistake in sublime text but it continues to display the error in sublime. The shell displays correct.

Saving the document doesn't help.

But typing something into sublime seems to kick off its refresh and now it updates to the correct value ie. no error

...

Another test, now I pass in a string, FORCING A SAVE, sublime shows no errors, executing in the shell shows

/Users/ian/Desktop/start/flight/test.js:8:5,10: string
This type is incompatible with
  /Users/ian/Desktop/start/flight/test.js:5:10,15: number

Found 1 error

Typing any text into the sublime text editor and pressing enter, kicks off the refresh and error is shown.

It appears for the shell even to detect changes you must save the file,

I have JSCS and JSHINT also installed you the sublime linter and these show the errors without saving, and correcting of errors without saving.

Does this help ?

**Comment by NicoSantangelo** [comment]
Aww yes, the problem is that right now, the package is using `flow check` to lint the file you're looking. `check` will look every file reading it from disk, not picking up the temporal changes Sublime Text makes.

The currently open pull requests try to fix this, but they're not merged yet, so this is a known limitation

**Comment by altdeveloper** [comment]
Ok Thanks @NicoSantangelo. I will keep my eye on any updates. Thanks for letting me know.
