### ISSUE TITLE
Support project-local flow binary

### ISSUE THREAD

**Issue by namuol** [SublimeLinter/SublimeLinter-flow#33]
Currently users are required to have `flow` in their `PATH`, which usually means a global install of flow:

```
npm install -g flow-bin
```

However, it's possible to use the project-local flow binary (i.e. `./node_modules/bin/flow`) by extending `NodeLinter` and supplying `npm_name`, [as seen here in **SublimeLinter-eslint**](https://github.com/roadhump/SublimeLinter-eslint/blob/3967ca67bc98d4e6df7ae2aca61add27443c6aaa/linter.py#L16-26).

Any reason not to do it this way? Seems like a good convention.

**Comment by ckaznocha** [comment]
Nope, I don't see any good reason not to do that. It should probably fall back to the PATH in any fringe case where folks don't have npm/node installed as flow doesn't actually require node. PRs welcome!
