### ISSUE TITLE
I’d like to help: `flow coverage`

### ISSUE THREAD

**Issue by davidaurelio** [SublimeLinter/SublimeLinter-flow#46]
I’d love to add optional support for `flow coverage` to SublimeLinter-flow. The problem is that we have to run an `flow coverage --path @ --json` as an *additional* command.

As far as I understand the SublimeLinter developer docs, there is no generic support for this. would it be feasible to override `run()` in a way that calls `super().run()` twice?

Thanks!

**Comment by ckaznocha** [comment]
Cool idea. What do you envision doing with the output? Calling `super().run()` seems like it could be worth trying as long as the result form each call is merged correctly into to whatever gets returned in `run()`.

**Comment by davidaurelio** [comment]
I would display warnings for uncovered code areas. But only if the users explicitly enables it with an option, otherwise it would get annoying pretty quickly.

**Comment by davidaurelio** [comment]
… I should proofread my texts first. I meant to write “there is **no** generic support for this” in the initial post. Corrected that.

Ok, I’m going to give it a go. It’s probably safest to copy `cmd` as received in `run`, and replace `'check-contents.` with `'coverage', '--path'`.

**Comment by ckaznocha** [comment]
Closed by #49
