### ISSUE TITLE
Flow Comment Type support?

### ISSUE THREAD

**Issue by brownieboy** [SublimeLinter/SublimeLinter-flow#54]
Does SublimeLinter-flow support [Flow's comment-based syntax](https://flow.org/en/docs/types/comments/)?  

I'm finding that it's giving me "Missing Type Annotation" errors for code like this:
```
// @flow
import React from "react";
import type { Element } from "react";

const InputField = (value /*: string */)/*: Element<*> */ => <input value={ value } />;
```

But if I remove the comments from the annotations, it passes Flow validation just fine.

**Comment by brownieboy** [comment]
My bad.

I actually had two linters enabled under Tools->SublimeLinter Toggler Linter.  These were "eslint" and "flow", with "flow" being the SublimeLinter-Flow package.  And it was actually the eslint linter rather than the flow linter that was giving me the errors above.  The flow linter enabled on its own works just fine, correctly flagging it when I removed my comment style annotations.

But now I've lost all my other eslint linting thought!  I need to find some way to make them work together, I guess.

**Comment by revolunet** [comment]
Hi, how does the Comment type support handle Types in multiple files ?
looks like i have to duplicate the definitions :/
