### ISSUE TITLE
Trouble with SublimeLinter-flow

### ISSUE THREAD

**Issue by liz-mars** [SublimeLinter/SublimeLinter-flow#55]
I can't get sublimelinter-flow to show errors in the gutter. Yet the flow executable is in my $PATH, sublimelinter debug mode says that the plugin is successfully loading and running, and reporting errors, but they don't show up in the editor view. sublimelinter-eslint, etc. all work without a glitch. Again, my path is configured correctly (in .bash_profile, as per the sublimelinter docs) and the plugin is correctly finding the flow executable.

Here's what the gutter looks like next to a line with a known Flow error (line 49)
![image](https://user-images.githubusercontent.com/315987/32354120-87d2798e-bfe5-11e7-9e96-c53502cbbbec.png)

Here's what the console says is going on:
![image](https://user-images.githubusercontent.com/315987/32354157-b234af3a-bfe5-11e7-8070-2746187ab37e.png)

Any help appreciated. Thanks for such an awesome product. <3

PS the yellow square is marking a change viz. my git history, ignore it.

**Comment by braver** [comment]
A lot has happened since this issue was opened. Hopefully we fixed this by now. If not, let us know (with full debug logs and settings of course).
