### ISSUE TITLE
SublimeLinter-Flow doesn't find '.flowconfig' between the open file and the directory root.

### ISSUE THREAD

**Issue by ryami333** [SublimeLinter/SublimeLinter-flow#61]
Until one of the latest releases, it would appear that SublimeLinter-Flow checked recursively checked all of the currently-opened-file's parent directories for presence of a `.flowconfig` file, which meant that the following directory structure would work:
```
- project-root
    - foo
        - .flowconfig
        - bar
            - the-open-file.js
```

Now, it does not. The error message suggests that it only starts looking from the project-root, rather than from the currently-opened-file. This means that I can no longer use SublimeLinter-Flow with a project whose `.flowconfig` is not at the project root.

**Comment by kaste** [comment]
We changed the default working dir. You can set working_dir to something different, e.g. ${file_path}, in your settings.

**Comment by ryami333** [comment]
So it used to determine the `.flowconfig` intelligently and now I have to hard-code it into my settings for every project?

**Comment by kaste** [comment]
But the example I made was not really hard-coded. 🤔
