### ISSUE TITLE
How can I fix this random Flow “WARNING” that pops up on every page?

### ISSUE THREAD

**Issue by ianizaguirre** [SublimeLinter/SublimeLinter-flow#62]
Every time I start a new project now, my sublime console , pops up 

```
WARNING: flow cannot locate 'flow'
```
I have no idea how I can fix this ?  This is a really big issue for me, because this pop up continues to pop up after I close it on every file of every project.

**Comment by kaste** [comment]
This should've been fixed in the most recent SublimeLinter versions. Try to trigger a manual update via PackageControl. And/Or restart sublime like ... 20 times or so.

**Comment by kaste** [comment]
Closing bc it should be fixed
