### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by dantman** [SublimeLinter/SublimeLinter-flow#63]
I'm trying to use flow with SublimeLinter and it's working.

However after awhile I get this error and have to restart sublime.
```
SublimeLinter: #219 flow UpdateHelpers.mjs ERROR:

 could not launch ['{app}/node_modules/.bin/flow', 'check-contents', '{app}/src/responsive-editor/js/store/template-helpers/UpdateHelpers.mjs', '--show-all-errors', '--json']
Reason: [Errno 24] Too many open files
PATH: /Users/daniel/.yarn/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/sbin:/usr/local/share/npm/bin:/Users/daniel/Library/Android/sdk/platform-tools
```

Is there a way to fix this?

**Comment by kaste** [comment]
How many threads are running at that time? How long does one lint job usually take? 

Possible fix https://github.com/SublimeLinter/SublimeLinter/pull/1234
Related https://github.com/SublimeLinter/SublimeLinter/issues/1201

**Comment by dantman** [comment]
```shell
$ time yarn flow -- check-contents src/responsive-editor/js/store/template-helpers/UpdateHelpers.mjs --show-all-errors --json < src/responsive-editor/js/store/template-helpers/UpdateHelpers.mjs
...
✨  Done in 0.52s.

real	0m0.883s
user	0m0.480s
sys	0m0.088s
```

How do I check the thread count?

**Comment by kaste** [comment]
> How do I check the thread count?

Each OS has its own program here. Doesn't need to be fancy. Maybe 'Process Monitor' / 'Task Monitor'. 

You could check out https://github.com/SublimeLinter/SublimeLinter/pull/1234

**Comment by nvtkaszpir** [comment]
https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

**Comment by kaste** [comment]
Closing old issue without movement.
