### ISSUE TITLE
esproposal.optional_chaining=enable

### ISSUE THREAD

**Issue by spointeau** [SublimeLinter/SublimeLinter-flow#67]
sublimelinter-flow is keeping telling me that the code is incorrect "o.toto?.titi" although the .flowconfig is having "esproposal.optional_chaining=enable"

(it works in webstorm)

what should I do for it to work in sublime text?

**Comment by spointeau** [comment]
where and how should I put the working_dir setting?

**Comment by spointeau** [comment]
BTW the js file in in the same directory than the .flowconfig (it is the app.js)

**Comment by kaste** [comment]
Search for SublimeLinter Settings in the Command Palette.

There you can enable debug mode, so you can actually see in the console what's happening.

In the default settings you also see an example of how to change the working dir for a specific linter.

**Comment by spointeau** [comment]
I guess the issue must be somewhere else because (after putting debug to true and setting the working_dir to "$file_path") I can see that the working_dir is correct (in the console) but linter-flow is still telling that the expression (o.toto?.titi) is incorrect.

**Comment by kaste** [comment]
While in debug mode, SublimeLinter logs the command it executes plus the working dir. How ist that command different from what webstorm executes.

You can also of course run this command in your Terminal/shell and play with it going from there. If you know the correct cmd using your shell, I'm pretty sure you can configure SublimeLinter for the win.

**Comment by spointeau** [comment]
thank you! I investigated on the command line directly, and I finally noticed that my code was incorrect.
I did put:
`
type mydatat = {
  toto?: {
    titi: string
  }
}
`
instead of 
`
type mydatat = {
  toto: ?{
    titi: string
  }
}
`

so this was my mistake.

(so now I don't understand why webstorm did not detect it...)

Thank you again for your help
